"""add otp secret

Revision ID: 053ef4ee87aa
Revises: a941bda4f3a8
Create Date: 2026-04-19 14:08:43.457006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '053ef4ee87aa'
down_revision: Union[str, Sequence[str], None] = 'a941bda4f3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(), nullable=True))
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'reset_token_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
