"""add verify email token

Revision ID: 079f53e2e01e
Revises: 4b37d27320e0
Create Date: 2026-04-07 08:57:15.908631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079f53e2e01e'
down_revision: Union[str, Sequence[str], None] = '4b37d27320e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.UUID(), nullable=True))
    op.create_unique_constraint('users_token_key', 'users', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_token_key', 'users', type_='unique')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
