"""change age to date_birth

Revision ID: 4b37d27320e0
Revises: 7c6810962c7b
Create Date: 2026-04-07 07:48:34.621087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b37d27320e0'
down_revision: Union[str, Sequence[str], None] = '7c6810962c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.alter_column('profiles', 'gender',
               existing_type=postgresql.ENUM('MAN', 'WOMEN', name='genderenum'),
               nullable=True)
    op.drop_column('profiles', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('profiles', 'gender',
               existing_type=postgresql.ENUM('MAN', 'WOMEN', name='genderenum'),
               nullable=False)
    op.drop_column('profiles', 'date_of_birth')
    # ### end Alembic commands ###
