"""add SportType Table

Revision ID: 624a971eb09b
Revises: ddcf1f939387
Create Date: 2026-05-26 18:16:44.149585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624a971eb09b'
down_revision: Union[str, Sequence[str], None] = 'ddcf1f939387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('events', sa.Column('sport_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'sport_types', ['sport_type_id'], ['id'])
    op.drop_column('events', 'sport_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sport_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'sport_type_id')
    op.drop_table('sport_types')
    # ### end Alembic commands ###
