"""make user token not null

Revision ID: f903ce7e814f
Revises: 079f53e2e01e
Create Date: 2026-04-07 09:01:56.892942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f903ce7e814f'
down_revision: Union[str, Sequence[str], None] = '079f53e2e01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Generate tokens for existing users
    op.execute("UPDATE users SET token = gen_random_uuid() WHERE token IS NULL")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
