from typing import Protocol


class JwtServiceInterface(Protocol):
    def create_access_token(self, data: dict) -> str: ...
    def create_refresh_token(self, data: dict) -> str: ...
    def decode_jwt(self, token: str | bytes) -> dict: ...
