from typing import Protocol

from sport_network_api.domain.user import User


class UserGatewayInterface(Protocol):
    async def get_by_id(self, user_id: int) -> User | None: ...
    
    async def get_by_username(self, username: str) -> User | None: ...
    
    async def get_by_email(self, email: str) -> User | None: ...
    
    async def create(self, user: User) -> User: ...
    
    async def update(self, user: User) -> User: ...
    
    async def delete(self, user_id: int) -> bool: ...
